// src/App.tsx
import { HTMLProps, useEffect, useImperativeHandle, useRef } from 'react';
import { LucideIcon, SunIcon, MoonIcon, AtSignIcon } from 'lucide-react';
import wavingHand from '../src/assets/Waving Hand.webp'
import { cn } from './utils';
import useAnimateInView from './useAnimateInView';
import { animate, motion, MotionValue, useMotionValue, useTransform } from 'framer-motion';
import GithubIcon from "./assets/github-181717.svg?react";
import LinkedinIcon from "./assets/linkedin-0A66C2.svg?react";
import YoutubeIcon from "./assets/youtube-FF0000.svg?react";
import useTheme from './useTheme';

declare global {
    function applyTheme(): void
}

export type Skill = {
    category: string,
    icon: LucideIcon,
    items: string[],
    description: string[],
    titleClassName: string,
    lineClassName: string,
    glowClassName: string
}

export type Experience = {
    title: string,
    company?: string,
    dates: string[],
    description: string
}

export default function App () {

    const seniority: number = (new Date).getFullYear() - 2013;

    const experiences: Experience[] = [
        {
            title: "Lead développeur web",
            company: "Oxance",
            dates: ["Aujourd'hui", "2016"],
            description: "Développement, maintenance et gestion de plusieurs projets web"
        }, {
            title: "Développeur/Animateur Web",
            company: "Laboratoire ALPA",
            dates: ["2016", "2013"],
            description: "Développement, maintenance et gestion de plusieurs projets web, contact auprès des clients"
        }, {
            title: "Développeur Web",
            company: "Novalto",
            dates: ["2013", "2012"],
            description: "Développement, maintenance et évolution d'un site e-commerce sous Drupal."
        }, {
            title: "Développeur/Animateur Web",
            company: "Laval (Canada)",
            dates: ["2011"],
            description: "Création de site web sous Joomla (développement, design, contenu, traduction), principalement pour des communes. Formation et création de documentation technique."
        }
    ];

    const training: Experience[] = [
        {
            title: "Licence Pro SIL",
            description: "Métiers de l'internet et des applications multimédia",
            dates: ["2013"]
        }, {
            title: "BTS IRIS",
            description: "Informatique et réseau pour l'industrie et les services",
            dates: ["2012"]
        }
    ];

    const mailMe = () => {
        location.href = "mailto:" + ["contact@quentindion", "me"].join(".");
    };

    const [theme, toggleTheme] = useTheme();

    useAnimateInView({
        ".motion-fade": {initial: {opacity: 0}, animate: {opacity: 1}},
        ".motion-fade-up": {initial: {opacity: 0, y: 25}, animate: {opacity: 1, y: 0}},
        ".motion-fade-down": {initial: {opacity: 0, y: -25}, animate: {opacity: 1, y: 0}},
        ".motion-fade-left": {initial: {opacity: 0, x: -25}, animate: {opacity: 1, x: 0}},
        ".motion-fade-right": {initial: {opacity: 0, x: 25}, animate: {opacity: 1, x: 0}},
        ".motion-fade-scale": {initial: {opacity: 0, scale: 0}, animate: {opacity: 1, scale: 1}}
    });

    const mouseX = useMotionValue(window.innerWidth / 2);
    const mouseY = useMotionValue((window.innerHeight / 2) + window.scrollY);

    useEffect(() => {

        const updateMousePosition = (event: MouseEvent) => {
            animate(mouseX, event.clientX, {duration: 0});
            animate(mouseY, event.clientY, {duration: 0});
        };

        window.addEventListener("mousemove", updateMousePosition);

        return () => {
            window.removeEventListener("mousemove", updateMousePosition);
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    return <>
        <div className="relative">
            <div className="absolute h-screen w-full bg-[radial-gradient(#71717a40_1px,transparent_1px)] [background-size:16px_16px] 
                [mask-image:radial-gradient(ellipse_50%_50%_at_50%_50%,#000_70%,transparent_100%)]"></div>
        </div>
        <article className="container p-0 grid grid-cols-[1rem_1fr_1rem] md:grid-cols-[2rem_1fr_2rem]">
            <div className="min-w-4 md:min-w-8 bg-dashed border-x dark:border-white/10 border-black/5" />
            <div>
                <section className="h-12"></section>
                <div className="flex flex-row items-start justify-between mx-2 md:mx-8">
                    <nav className="flex flex-wrap gap-2 justify-start">
                        <a className="button" href="https://github.com/quentindion" role="button" aria-label="Github">
                            <GithubIcon className="size-6 fill-current github-icon transition-colors" /> Github
                        </a>
                        <a className="button" href="https://www.youtube.com/@vs2kf" role="button" aria-label="Youtube">
                            <YoutubeIcon className="size-6 fill-current youtube-icon transition-colors" /> Youtube
                        </a>
                        <a className="button" href="https://www.linkedin.com/in/quentindion" role="button" aria-label="LinkedIn">
                            <LinkedinIcon className="size-6 fill-current linkedin-icon transition-colors" /> LinkedIn
                        </a>
                        <a className="button" onClick={mailMe} role="button" aria-label="Mail">
                            <AtSignIcon className="transition-colors" /> Mail
                        </a>
                    </nav>
                    <div>
                        <button className="relative button-icon" onClick={toggleTheme} aria-label="Thème">
                            <div className="relative inline-flex gap-2 items-center">
                                {(theme === "dark" && window.matchMedia("screen").matches) || (!theme && window.matchMedia("screen and (prefers-color-scheme: dark)").matches) ?
                                    <SunIcon /> :
                                    <MoonIcon />}
                            </div>
                        </button>
                    </div>
                </div>

                <section className="relative mt-20 md:mt-32 px-2">
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                    <div className="font-medium text-lg text-neutral-600 dark:text-neutral-400 motion-fade-up">
                        Hello <img src={wavingHand} alt="Waving hand" className="inline size-8 align-text-bottom" />, je suis Quentin Dion
                    </div>
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                    <h1 className="mb-2 motion-fade-up drop-shadow-md dark:shadow-black">
                        Lead Web
                        <span className="text-gradient-primary"> Developer</span>
                    </h1>
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                    <p className="font-medium text-lg max-w-(--breakpoint-md) text-neutral-600 dark:text-neutral-400 motion-fade-up">
                        Depuis {seniority} ans, passionné d’informatique et des nouvelles technologies qui font le web d'aujourd'hui.
                    </p>
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                </section>

                <section className="relative mt-20 md:mt-32 px-2">
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                    <h2 className="pt-2 motion-fade-up">Compétences</h2>
                    <div className="flex flex-wrap items-stretch justify-start gap-2 py-2">
                        <div className="flex-[1_1_28rem] motion-fade-scale">
                            <Card className="h-full" mouseX={mouseX} mouseY={mouseY}>
                                <h3>Interface Web & UI</h3>
                                <div className="labels mb-4">
                                    <div className="label">React</div>
                                    <div className="label">Angular</div>
                                    <div className="label">HTML</div>
                                    <div className="label">Sass</div>
                                    <div className="label">Tailwind</div>
                                </div>
                                <p className="relative text-pretty">
                                    Développement de <span className="font-semibold">PWA </span>
                                    et <span className="font-semibold">d'interfaces utilisateur </span>
                                    pour de la gestion métier (planifications, gestion de ressources internes).
                                </p>
                            </Card>
                        </div>
                        <div className="flex-[1_1_28rem] motion-fade-scale">
                            <Card className="h-full" mouseX={mouseX} mouseY={mouseY}>
                                <h3>Base de donnée & BI</h3>
                                <div className="labels mb-4">
                                    <div className="label">Qlik Sense</div>
                                    <div className="label">Power BI</div>
                                    <div className="label">MSSQL</div>
                                    <div className="label">Postgres</div>
                                    <div className="label">MongoDB</div>
                                    <div className="label">Supabase</div>
                                </div>
                                <p className="relative text-pretty">
                                    Gestion de <span className="font-semibold">bases de données </span>
                                    pour des applications temps réel et agrégation de données multi-plateformes en indicateurs de gestion pour des
                                    <span className="font-semibold"> rapports BI </span>
                                    publiés aux collaborateurs.
                                </p>
                            </Card>
                        </div>
                        <div className="flex-[1_1_28rem] motion-fade-scale">
                            <Card className="h-full" mouseX={mouseX} mouseY={mouseY}>
                                <h3>Applications & API</h3>
                                <div className="labels mb-4">
                                    <div className="label">PHP</div>
                                    <div className="label">Laravel</div>
                                    <div className="label">NodeJS</div>
                                    <div className="label">ElectronJS</div>
                                </div>
                                <p className="relative text-pretty">
                                    Développement d'<span className="font-semibold">API </span>
                                    backend pour intranet et applications mobiles, d'
                                    <span className="font-semibold">applications de bureau </span>
                                    et de tâches automatiques d'intégration de données.
                                </p>
                            </Card>
                        </div>
                        <div className="flex-[1_1_28rem] motion-fade-scale">
                            <Card className="h-full" mouseX={mouseX} mouseY={mouseY}>
                                <h3>CMS</h3>
                                <div className="labels">
                                    <div className="label mb-4">Wordpress</div>
                                </div>
                                <p className="relative text-pretty">
                                    Maintenance de sites internet et développement de plugins et thèmes sous
                                    <span className="font-semibold"> Wordpress</span>.
                                </p>
                            </Card>
                        </div>
                    </div>
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                </section>

                <section className="relative mt-20 md:mt-32 px-2">
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                    <h2 className="pt-2 motion-fade-up">Expériences</h2>
                    <Timeline items={experiences} className="py-2" />
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                </section>

                <section className="relative mt-20 md:mt-32 px-2">
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                    <h2 className="pt-2 motion-fade-up">Formations</h2>
                    <Timeline items={training} className="py-2" />
                    <div className="absolute -left-[100vw] w-[200vw] border-b dark:border-white/10 border-black/5" />
                </section>

                <section className="h-36"></section>
            </div>

            <div className="min-w-4 md:min-w-8 bg-dashed border-x dark:border-white/10 border-black/5" />
        </article>
    </>
}    

const Card = motion.create((
    {children, className, mouseX, mouseY, ref: forwardedRef}: 
    HTMLProps<HTMLElement> & {mouseX: MotionValue<number>, mouseY: MotionValue<number>}
) => {

    const ref = useRef<HTMLDivElement>(null);
    useImperativeHandle(forwardedRef, () => ref.current as HTMLDivElement);

    const refX = useMotionValue(0);
    const refY = useMotionValue(0);

    const updateRefPosition = () => {
        if(ref.current) {
            refX.set(ref.current.getBoundingClientRect().left);
            refY.set(ref.current.getBoundingClientRect().top);
        }
    }

    useEffect(() => {
        updateRefPosition();
        window.addEventListener("scroll", updateRefPosition);

        return () => {
            window.removeEventListener("scroll", updateRefPosition);
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

    const relativeX = useTransform<number, string>([mouseX, refX], ([mouseX, refX]) => `${ref.current ? mouseX - refX : mouseX}px`);
    const relativeY = useTransform<number, string>([mouseY, refY], ([mouseY, refY]) => `${ref.current ? mouseY - refY : mouseY}px`);

    return <motion.div ref={ref} className={cn("card", className)} style={{
        "--spotlight-x": relativeX,
        "--spotlight-y": relativeY,
    }}>
        <div className="card-content transition-all">{children}</div>
    </motion.div>
});

const Timeline = ({items, className}: HTMLProps<HTMLElement> & {items: Experience[]}) =>
    <div className={className}>
        {items.map(({dates, title, company, description}, i) => <div key={i} className="relative flex flex-col">
            {dates[0] && <h3 className="my-4 max-w-30 md:text-right motion-fade-right text-neutral-600 dark:text-neutral-400">{dates[0]}</h3>}            
            <div className="relative flex flex-col items-start ml-8 md:ml-40">
                <div className="absolute -top-1 -left-5 md:-left-14 h-[calc(100%_+_0.75rem)] w-[1px] dark:bg-white/10 bg-black/5"></div>
                <h3 className="motion-fade-left">{title}</h3>
                {company && <h3 className="text-gradient-primary motion-fade-left">{company}</h3>}
                <p className="leading-4 motion-fade-left">{description}</p>
            </div>
            {dates[1] && (dates[1] !== items[i + 1].dates[0]) && 
                <h3 className="my-4 max-w-30 md:text-right motion-fade-right text-neutral-600 dark:text-neutral-400">{dates[1]}</h3>}
        </div>)}
    </div>;

// src/app/app.component.ts
import { AfterViewInit, Component, HostListener } from '@angular/core';
import { FeatherIconNames } from 'feather-icons';
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../../tailwind.config';
import { Config, KeyValuePair } from 'tailwindcss/types/config';
import { Observable, fromEvent, map, startWith } from 'rxjs';
import Scrollreveal from 'scrollreveal';
import { panelAnimation } from './dropdown-trigger-for.directive';

export type Theme = undefined | 'light' | 'dark';
export type ThemableWindow = Window & typeof globalThis & {updateTheme: Function};

@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html',
    animations: [panelAnimation]
})
export class AppComponent implements AfterViewInit  {

    @HostListener('window:scroll') onScroll () {

        this.navScrollProgress = ((document.documentElement.scrollTop - 80) / 176 * 100).clamp(0, 100);
    }

    @HostListener('window:resize') onResize () {

        const breakpoints: KeyValuePair = this.config.theme?.screens as KeyValuePair;

        this.isMd = matchMedia(`(min-width: ${breakpoints['sm']})`).matches;
    }

    private config: Config = resolveConfig(tailwindConfig);

    navScrollProgress: number = 0

    seniority: number = (new Date).getFullYear() - 2013;

    skills: {category: string, icon: FeatherIconNames, items: string[], description: string}[] = [
        {
            category: 'BI',
            icon: 'bar-chart-2',
            items: ['Qlik Sense', 'Power BI'],
            description: 'Collecte et agrégation de données multi-plateformes en indicateurs de gestion et publication de rapports aux collaborateurs.'
        },
        {
            category: 'Interface Web',
            icon: 'layout',
            items: ['HTML', 'CSS', 'JS', 'Angular', 'Tailwind'],
            description: 'Développement de PWA et d\'interfaces utilisateur pour de la gestion métier (planifications, gestion de ressources internes).'
        },
        {
            category: 'Langage Serveur',
            icon: 'server',
            items: ['PHP', 'NodeJS', 'Laravel'],
            description: 'Développement d\'applications backend de gestion, d\'API Rest pour applications mobiles et gestion de tâches automatiques entre systèmes.'
        },
        {
            category: 'Base de donnée',
            icon: 'database',
            items: ['SQL', 'MongoDB', 'Redis'],
            description: 'Développement de requêtes et de modèles de base de donnée pour des applications temps réel et des rapports BI.'
        },
        {
            category: 'CMS',
            icon: 'globe',
            items: ['Wordpress'],
            description: 'Maintenance de sites internet et développement de thèmes et plugins sous Wordpress.'
        }
    ];

    experiences: {title: string, company: string, dates: string[], description: string}[] = [
        {
            title: 'Lead développeur web',
            company: 'Oxance',
            dates: ['2016'],
            description: 'Développement, maintenance et gestion de plusieurs projets web'
        }, {
            title: 'Développeur/Animateur Web',
            company: 'Laboratoire ALPA',
            dates: ['2016', '2013'],
            description: 'Développement, maintenance et gestion de plusieurs projets web, contact auprès des clients'
        }, {
            title: 'Développeur Web',
            company: 'Novalto',
            dates: ['2013', '2012'],
            description: 'Développement, maintenance et évolution d\'un site e-commerce sous Drupal.'
        }, {
            title: 'Développeur/Animateur Web',
            company: 'Laval (Canada)',
            dates: ['2011'],
            description: 'Création de site web sous Joomla (développement, design, contenu, traduction), principalement pour des communes. Formation et création de documentation technique.'
        }
    ];

    training: {description: string, company: string, dates: string[]}[] = [
        {
            company: 'Licence Pro SIL',
            description: 'Métiers de l\'internet et des applications multimédia',
            dates: ['2013', '2012']
        }, {
            company: 'BTS IRIS',
            description: 'Informatique et réseau pour l\'industrie et les services',
            dates: ['2012', '2010']
        }
    ];

    themes: {name: string, icon?: FeatherIconNames, icons?: FeatherIconNames[], action: Function}[] = [
        {name: 'Clair', icon: 'sun', action: () => this.setTheme('light')},
        {name: 'Sombre', icon: 'moon', action: () => this.setTheme('dark')},
        {name: 'Système', icons: ['sun', 'moon'], action: () => this.setTheme(undefined)}
    ];

    theme: Theme = localStorage.getItem('theme') as Theme;

    isMd: boolean = false;

    constructor() { 
        
        this.onResize();

        this.onMedia('(prefers-color-scheme: dark)')
            .subscribe(() => setTimeout(() => (window as ThemableWindow).updateTheme(), 0));
    }

    ngAfterViewInit(): void {

        if(!matchMedia('print').matches && !matchMedia('(prefers-reduced-motion)').matches) {
            Scrollreveal().reveal('.reveal-profile .reveal', {interval: 100, distance: '80px'});
            Scrollreveal().reveal('.reveal-cards .reveal-title', {interval: 100, distance: '80px', origin: 'right'});
            Scrollreveal().reveal('.reveal-cards .reveal', {interval: 100, scale: .8, opacity: 0});
            Scrollreveal().reveal('.reveal-list .reveal-title', {interval: 100, distance: '80px', origin: 'right'});
            Scrollreveal().reveal('.reveal-list .reveal-date', {interval: 100, opacity: 0});
            Scrollreveal().reveal('.reveal-list .reveal', {interval: 100, distance: '80px', origin: 'right'});
        }
    }

    mailMe () {
        location.href = 'mailto:' + ['contact@quentindion', 'me'].join('.');
    }

    setTheme (value: Theme) {

        if(value) localStorage.setItem('theme', value);
        else localStorage.removeItem('theme');

        this.theme = value;

        (window as ThemableWindow).updateTheme();
    }

    onMedia (query: string): Observable<Boolean> {

        const mediaQuery = matchMedia(query);
        
        return fromEvent<MediaQueryList>(mediaQuery, 'change').pipe(
            startWith(mediaQuery),
            map((list: MediaQueryList) => list.matches)
        );
    }
}

<ng-template #themeMenuTemplate>
    <ul class="p-3 my-2 rounded-3xl shadow-primer-xl bg-white dark:text-gray-200 dark:bg-gray-900" @panel>
        <li *ngFor="let item of themes" (click)="item.action()"
            class="button font-normal">
            <ng-container [ngSwitch]="item.icon">
                <i *ngIf="item.icon" class="inline-block align-sub mr-2">{{item.icon}}</i>
                <span *ngIf="item.icons" class="inline-block align-text-bottom mr-2 feather-mix-to-br">
                    <i *ngFor="let icon of item.icons" class="text-gray-800 dark:text-gray-200">{{icon}}</i>
                </span>
                {{item.name}}
            </ng-container>
        </li>
    </ul>
</ng-template>

<ng-template #timelineTemplate let-items>
    <div class="w-full grid grid-cols-1-1-3 gap-6">
        <ng-container *ngFor="let item of items">
            <div>
                <h3 class="text-gray-600 dark:text-gray-400 text-right text-2xl md:text-3xl reveal-date" *ngFor="let date of item.dates">{{date}}</h3>
            </div>
            <span class="w-full h-0.5 mt-5 border-b-4 border-gray-300 dark:border-gray-700 border-dotted reveal-date"></span>
            <div>
                <h3 class="text-gray-700 dark:text-gray-300 text-3xl md:text-4xl mb-5 reveal">{{item.company}}</h3>
                <h4 class="font-medium text-gray-700 dark:text-gray-300 text-lg mb-4 reveal">{{item.title}}</h4>
                <p class="text-gray-600 dark:text-gray-400 text-sm md:text-base reveal">{{item.description}}</p>
            </div>
        </ng-container>
    </div>
</ng-template>

<section class="h-20"></section>

<section class="mx-auto sticky top-0 z-10 max-w-screen-xl container backdrop-blur-md"
    [ngStyle]="{
        'maxWidth.%': navScrollProgress.percentBetween(isMd ? 50 : 75, 100),
        'borderRadius.px': navScrollProgress.percentBetween(0, 40, true),
        'backgroundColor': 'rgb(var(--nav-background-color) / '+ navScrollProgress.percentBetween(0, 50) +'%)',
        'boxShadow': '0 '+ navScrollProgress.percentBetween(0, 8) +'px '+ navScrollProgress.percentBetween(0, 24) +'px 0 rgb(var(--shadow-primer-color) / 20%)'
    }">
    <nav class="flex items-center justify-between p-4">
        <div class="flex flex-row gap-2">
            <a class="icon button rounded-full" (click)="mailMe()" role="navigation" aria-label="Mail">
                <i>at-sign</i>
            </a>
            <a class="icon button rounded-full" href="https://www.linkedin.com/in/quentindion" role="navigation" aria-label="LinkedIn">
                <i>linkedin</i>
            </a>
            <a class="icon button rounded-full" href="https://github.com/quentindion" role="navigation" aria-label="Github">
                <i>github</i>
            </a>
            <a class="icon button rounded-full" href="https://www.youtube.com/@vs2kf" role="navigation" aria-label="Youtube">
                <i>youtube</i>
            </a>
        </div>
        <div class="flex gap-2">
            <button [dropdownTriggerFor]="themeMenuTemplate" class="icon rounded-full" aria-label="Switch dark mode">
                <span class="feather-mix-to-br">
                    <i class="text-gray-800 dark:text-gray-200">sun</i>
                    <i class="text-gray-800 dark:text-gray-200">moon</i>
                </span>
            </button>
        </div>
    </nav>
</section>

<section class="justify-center py-10 md:py-16 reveal-profile">

    <img src= "assets/profil.webp" alt="Image" class="h-[262px] w-[262px] mx-auto my-8 object-cover object-[center_60%] rounded-full reveal" loading="lazy" />
    <h1 class="flex justify-center text-gray-600 dark:text-gray-400 text-lg md:text-2xl mb-8 reveal">Quentin Dion</h1>

    <h2 class="flex justify-center md:font-light text-4xl md:text-7xl leading-none mb-8 text-transparent bg-clip-text
        bg-gradient-to-br from-lime-300 to-gray-300 to-50% dark:from-lime-300/50 dark:to-gray-700 reveal">Lead Web Developer</h2>
    <p class="flex justify-center text-gray-600 dark:text-gray-400 mb-10 md:mb-16 px-4 reveal">
        Depuis {{seniority}}ans, passionné d’informatique et des nouvelles technologies qui font le web d'aujourd'hui
    </p>
    <div class="mouse mx-auto reveal"></div>
</section>

<section class="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 reveal-cards">
    <h3 class="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl mb-5 reveal-title">Compétences</h3>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div *ngFor="let skill of skills" class="bg-gray-50 dark:bg-gray-900 px-6 py-8 rounded-xl shadow-primer-lg reveal">
            <div class="flex flex-row items-start gap-4">
                <i class="w-20 min-w-[5rem] py-6 flex justify-center bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 rounded-xl mb-4 shadow-inner">
                    {{skill.icon}}
                </i>
                <div>
                    <h4 class="font-medium text-gray-700 dark:text-gray-300 text-lg mb-4">{{skill.category}}</h4>
                    <div class="text-gray-600 dark:text-gray-400 text-md flex flex-row flex-wrap gap-1">
                        <span *ngFor="let item of skill.items" class="bg-gray-100 dark:bg-gray-800 text-xs text-center font-medium px-2 py-1 rounded-xl">
                            {{item}}
                        </span>
                    </div>
                </div>
            </div>
            <p class="text-gray-600 dark:text-gray-400 text-md">{{skill.description}}</p>
        </div>
    </div>
</section>
    
<section class="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 reveal-list">
    <div class="flex flex-col lg:flex-row justify-between gap-6">
        <div class="mb-10 lg:mb-0">
            <h3 class="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl reveal-title">Expériences</h3>
        </div>
        <ng-container *ngTemplateOutlet="timelineTemplate; context: {$implicit: experiences}"></ng-container>
    </div>
</section>

<section class="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 reveal-list">
    <div class="flex flex-col lg:flex-row justify-between gap-6">
        <div class="mb-10 lg:mb-0">
            <h3 class="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl reveal-title">Formations</h3>
        </div>
        <ng-container *ngTemplateOutlet="timelineTemplate; context: {$implicit: training}"></ng-container>
    </div>
</section>
