// src/components/App.tsx
import { useState } from 'react';
import { LucideIcon, BarChart2, Layout, Server, Database, Globe, Palette, Sun, Moon, SunMoon } from 'lucide-react';
import { Menu } from '@headlessui/react';
import { AnimatePresence, motion, useScroll, useTransform } from "framer-motion";
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../../tailwind.config.js';
import Lottie from 'lottie-react';
import Timeline from './Timeline.js';
import githubIconAnimation from '../assets/github.json';
import linkedinIconAnimation from '../assets/linkedin.json';
import mailIconAnimation from '../assets/mail.json';
import youtubeIconAnimation from '../assets/youtube.json';
import scrollDownIconAnimation from '../assets/scrollDown.json';
import LottieIcon from './LottieIcon.js';
import profilImg from '../assets/profil.webp';
import { Config } from 'tailwindcss';
import { useMediaQuery } from 'react-responsive';
import useInView from '../hooks/inView.js';

export type Theme = null | 'light' | 'dark';

export type Skill = {
    category: string,
    icon: LucideIcon,
    items: string[],
    description: string
}

export type Experience = {
    title?: string,
    company: string,
    dates: string[],
    description: string
}

export default function App () {

    const seniority: number = (new Date).getFullYear() - 2013;

    const skills: Skill[] = [
        {
            category: 'BI',
            icon: BarChart2,
            items: ['Qlik Sense', 'Power BI'],
            description: 'Collecte et agrégation de données multi-plateformes en indicateurs de gestion et publication de rapports aux collaborateurs.'
        },
        {
            category: 'Interface Web',
            icon: Layout,
            items: ['HTML', 'CSS', 'JS', 'React', 'Angular', 'Tailwind'],
            description: 'Développement de PWA et d\'interfaces utilisateur pour de la gestion métier (planifications, gestion de ressources internes).'
        },
        {
            category: 'Langage Serveur',
            icon: Server,
            items: ['PHP', 'NodeJS', 'Laravel'],
            description: 'Développement d\'applications backend de gestion, d\'API Rest pour applications mobiles et gestion de tâches automatiques entre systèmes.'
        },
        {
            category: 'Base de donnée',
            icon: Database,
            items: ['SQL', 'MongoDB', 'Redis'],
            description: 'Développement de requêtes et de modèles de base de donnée pour des applications temps réel et des rapports BI.'
        },
        {
            category: 'CMS',
            icon: Globe,
            items: ['Wordpress'],
            description: 'Maintenance de sites internet et développement de thèmes et plugins sous Wordpress.'
        }
    ];

    const experiences: Experience[] = [
        {
            title: 'Lead développeur web',
            company: 'Oxance',
            dates: ['2016'],
            description: 'Développement, maintenance et gestion de plusieurs projets web'
        }, {
            title: 'Développeur/Animateur Web',
            company: 'Laboratoire ALPA',
            dates: ['2016', '2013'],
            description: 'Développement, maintenance et gestion de plusieurs projets web, contact auprès des clients'
        }, {
            title: 'Développeur Web',
            company: 'Novalto',
            dates: ['2013', '2012'],
            description: 'Développement, maintenance et évolution d\'un site e-commerce sous Drupal.'
        }, {
            title: 'Développeur/Animateur Web',
            company: 'Laval (Canada)',
            dates: ['2011'],
            description: 'Création de site web sous Joomla (développement, design, contenu, traduction), principalement pour des communes. Formation et création de documentation technique.'
        }
    ];

    const training: Experience[] = [
        {
            company: 'Licence Pro SIL',
            description: 'Métiers de l\'internet et des applications multimédia',
            dates: ['2013', '2012']
        }, {
            company: 'BTS IRIS',
            description: 'Informatique et réseau pour l\'industrie et les services',
            dates: ['2012', '2010']
        }
    ];

    const mailMe = () => {
        location.href = 'mailto:' + ['contact@quentindion', 'me'].join('.');
    }

    const {theme: {screens}} = resolveConfig(tailwindConfig) as {theme: Partial<Config>};

    const isMd = useMediaQuery({query: `(min-width: ${screens.md})`});

    const themes: {name: string, icon: LucideIcon, action: () => void}[] = [
        {name: 'Clair', icon: Sun, action: () => updateTheme('light')},
        {name: 'Sombre', icon: Moon, action: () => updateTheme('dark')},
        {name: 'Système', icon: SunMoon, action: () => updateTheme(null)}
    ];

    const [_theme, setTheme] = useState<Theme>(localStorage.getItem('theme') as Theme);

    const updateTheme = (theme: Theme) => {

        setTheme(theme);

        if(theme) localStorage.setItem('theme', theme);
        else localStorage.removeItem('theme');

        window.applyTheme();
    }

    const { scrollY } = useScroll();

    const navScrollYProgress = useTransform(scrollY, [80, 400], [0, 1]);

    const navMaxWidth = useTransform(navScrollYProgress, [0, 1], [`${isMd ? 50 : 75}%`, '100%']);
    const navBgOpacity = useTransform(navScrollYProgress, [0, 1], [0, 0.75]);
    const navBorderRadius = useTransform(navScrollYProgress, [0, 1], [40, 0]);
    const navShadowOpacity = useTransform(navScrollYProgress, [0, 1], [
        '0 0px 0px -5px var(--tw-shadow-color), 0 0px 0px -5px var(--tw-shadow-color)',
        '0 20px 25px -5px var(--tw-shadow-color), 0 20px 25px -5px var(--tw-shadow-color)'
    ]);

    const menuAnimations = {
        hidden: {
            scale: 0,
            opacity: 0
        },
        visible: {
            scale: 1,
            opacity: 1,
            transition: {
                // type: 'spring',
                delayChildren: 0.15,
                staggerChildren: 0.05,
            }
        },
        exit: {opacity: 0}
    };

    const menuItemAnimation = {
        hidden: {y: 25, opacity: 0},
        visible: {y: 0, opacity: 1},
        exit: {opacity: 0}
    };

    useInView('.motion-fade', {initial: {opacity: 0}, animate: {opacity: 1}});
    useInView('.motion-fade-up', {initial: {opacity: 0, y: 75}, animate: {opacity: 1, y: 0}});
    useInView('.motion-fade-left', {initial: {opacity: 0, x: -75}, animate: {opacity: 1, x: 0}});
    useInView('.motion-fade-right', {initial: {opacity: 0, x: 75}, animate: {opacity: 1, x: 0}});
    useInView('.motion-fade-scale', {initial: {opacity: 0, scale: 0}, animate: {opacity: 1, scale: 1}});

    return <>
        <section className="h-20"></section>
        <motion.section className="mx-auto sticky top-0 z-10 max-w-screen-xl container backdrop-blur-md min-w-[75%] md:min-w-[50%]
            bg-gray-100 shadow-xl shadow-gray-500/25 dark:bg-gray-800 dark:shadow-black/25 motion-fade-up"
            style={{
                maxWidth: navMaxWidth,
                borderRadius: navBorderRadius,
                '--tw-shadow-colored': navShadowOpacity,
                '--tw-bg-opacity': navBgOpacity
            }}>
            <nav className="relative flex items-center justify-between p-2">
                <div className="flex flex-row gap-2">
                    <a className="button-icon dark:hover:after:bg-gray-700" onClick={mailMe} role="navigation" aria-label="Mail">
                        <LottieIcon animationData={mailIconAnimation} />
                    </a>
                    <a className="button-icon dark:hover:after:bg-gray-700" href="https://www.linkedin.com/in/quentindion" role="navigation" aria-label="LinkedIn">
                        <LottieIcon animationData={linkedinIconAnimation} />
                    </a>
                    <a className="button-icon dark:hover:after:bg-gray-700" href="https://github.com/quentindion" role="navigation" aria-label="Github">
                        <LottieIcon animationData={githubIconAnimation} />
                    </a>
                    <a className="button-icon dark:hover:after:bg-gray-700" href="https://www.youtube.com/@vs2kf" role="navigation" aria-label="Youtube">
                        <LottieIcon animationData={youtubeIconAnimation} />
                    </a>
                </div>
                <Menu as="div">
                    <Menu.Button className="button-icon hover:after:bg-gray-200 dark:hover:after:bg-gray-700">
                        <Palette />
                    </Menu.Button>
                    <AnimatePresence>
                        <Menu.Items className="absolute top-2 right-2 w-full sm:w-auto">
                            <motion.div key="theme-menu" 
                                className="flex flex-col outline-none p-2 shadow-xl rounded-xl overflow-hidden bg-gray-50 dark:bg-gray-900 origin-top-right"
                                initial="hidden" animate="visible" exit="exit" variants={menuAnimations}>
                                {themes.map(({name, icon, action}, i) => {
                                    const LucideIcon = icon;
                                    return <Menu.Item key={'theme-menu-item' + i}>
                                        <motion.button onClick={action} className="text-left z-[1]" variants={menuItemAnimation}>
                                            <LucideIcon /> {name}
                                        </motion.button>
                                    </Menu.Item>;
                                })}
                            </motion.div>
                        </Menu.Items>
                    </AnimatePresence>
                </Menu>
            </nav>
        </motion.section>
        <section className="justify-center py-10 md:py-16">
            <img src={profilImg} alt="Image" loading="lazy"
                className="h-[262px] w-[262px] mx-auto my-8 object-cover object-[center_60%] rounded-full motion-fade-up" />
            
            <h1 className="flex justify-center text-gray-600 dark:text-gray-400 text-lg md:text-2xl mb-8 motion-fade-up">Quentin Dion</h1>

            <h2 className="flex justify-center md:font-light text-4xl md:text-7xl leading-none mb-8 text-transparent bg-clip-text
                bg-gradient-to-br from-emerald-600 to-lime-500 dark:from-emerald-500 dark:to-lime-300 motion-fade-up">
                Lead Web Developer
            </h2>

            <p className="flex justify-center text-gray-600 dark:text-gray-400 mb-10 md:mb-16 px-4 motion-fade-up">
                Depuis {seniority}ans, passionné d’informatique et des nouvelles technologies qui font le web d'aujourd'hui
            </p>

            <Lottie animationData={scrollDownIconAnimation} className="lottie lottie-icon mx-auto w-10 text-gray-500 motion-fade-up" />
        </section>

        <section className="container max-w-screen-xl mx-auto px-4 py-10 md:py-16">
            <h3 className="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl mb-5 motion-fade-left">Compétences</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {skills.map(({category, items, description, icon}, i) => {

                    const LucideIcon = icon;
                    
                    return <div key={'skill-' + i} className="bg-gray-50 dark:bg-gray-900 px-6 py-8 rounded-xl shadow-primer-lg motion-fade-scale">
                        <div className="flex flex-row items-start gap-4">
                            <div className="w-20 min-w-[5rem] py-6 flex justify-center bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 rounded-xl mb-4 shadow-inner">
                                <LucideIcon />
                            </div>
                            <div>
                                <h4 className="font-medium text-gray-700 dark:text-gray-300 text-lg mb-4">{category}</h4>
                                <div className="text-gray-600 dark:text-gray-400 text-md flex flex-row flex-wrap gap-1">
                                    {items.map((item, j) =>
                                        <span key={'skill-item-' + j} className="bg-gray-100 dark:bg-gray-800 text-xs text-center font-medium px-2 py-1 rounded-xl">
                                            {item}
                                        </span>
                                    )}
                                </div>
                            </div>
                        </div>
                        <p className="text-gray-600 dark:text-gray-400 text-md">{description}</p>
                    </div>
                })}
            </div>
        </section>
            
        <section className="container max-w-screen-xl mx-auto px-4 py-10 md:py-16">
            <div className="flex flex-col lg:flex-row justify-between gap-6">
                <div className="mb-10 lg:mb-0">
                    <h3 className="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl motion-fade-left">Expériences</h3>
                </div>
                <Timeline experiences={experiences} />
            </div>
        </section>

        <section className="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 mb-12">
            <div className="flex flex-col lg:flex-row justify-between gap-6">
                <div className="mb-10 lg:mb-0">
                    <h3 className="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl motion-fade-left">Formations</h3>
                </div>
                <Timeline experiences={training} />
            </div>
        </section>
    </>
}

// src/app/app.component.ts
import { AfterViewInit, Component, HostListener } from '@angular/core';
import { FeatherIconNames } from 'feather-icons';
import resolveConfig from 'tailwindcss/resolveConfig';
import tailwindConfig from '../../tailwind.config';
import { Config, KeyValuePair } from 'tailwindcss/types/config';
import { Observable, fromEvent, map, startWith } from 'rxjs';
import Scrollreveal from 'scrollreveal';
import { panelAnimation } from './dropdown-trigger-for.directive';

export type Theme = undefined | 'light' | 'dark';
export type ThemableWindow = Window & typeof globalThis & {updateTheme: Function};

@Component({
    selector: 'app-root',
    templateUrl: 'app.component.html',
    animations: [panelAnimation]
})
export class AppComponent implements AfterViewInit  {

    @HostListener('window:scroll') onScroll () {

        this.navScrollProgress = ((document.documentElement.scrollTop - 80) / 176 * 100).clamp(0, 100);
    }

    @HostListener('window:resize') onResize () {

        const breakpoints: KeyValuePair = this.config.theme?.screens as KeyValuePair;

        this.isMd = matchMedia(`(min-width: ${breakpoints['sm']})`).matches;
    }

    private config: Config = resolveConfig(tailwindConfig);

    navScrollProgress: number = 0

    seniority: number = (new Date).getFullYear() - 2013;

    skills: {category: string, icon: FeatherIconNames, items: string[], description: string}[] = [
        {
            category: 'BI',
            icon: 'bar-chart-2',
            items: ['Qlik Sense', 'Power BI'],
            description: 'Collecte et agrégation de données multi-plateformes en indicateurs de gestion et publication de rapports aux collaborateurs.'
        },
        {
            category: 'Interface Web',
            icon: 'layout',
            items: ['HTML', 'CSS', 'JS', 'Angular', 'Tailwind'],
            description: 'Développement de PWA et d\'interfaces utilisateur pour de la gestion métier (planifications, gestion de ressources internes).'
        },
        {
            category: 'Langage Serveur',
            icon: 'server',
            items: ['PHP', 'NodeJS', 'Laravel'],
            description: 'Développement d\'applications backend de gestion, d\'API Rest pour applications mobiles et gestion de tâches automatiques entre systèmes.'
        },
        {
            category: 'Base de donnée',
            icon: 'database',
            items: ['SQL', 'MongoDB', 'Redis'],
            description: 'Développement de requêtes et de modèles de base de donnée pour des applications temps réel et des rapports BI.'
        },
        {
            category: 'CMS',
            icon: 'globe',
            items: ['Wordpress'],
            description: 'Maintenance de sites internet et développement de thèmes et plugins sous Wordpress.'
        }
    ];

    experiences: {title: string, company: string, dates: string[], description: string}[] = [
        {
            title: 'Lead développeur web',
            company: 'Oxance',
            dates: ['2016'],
            description: 'Développement, maintenance et gestion de plusieurs projets web'
        }, {
            title: 'Développeur/Animateur Web',
            company: 'Laboratoire ALPA',
            dates: ['2016', '2013'],
            description: 'Développement, maintenance et gestion de plusieurs projets web, contact auprès des clients'
        }, {
            title: 'Développeur Web',
            company: 'Novalto',
            dates: ['2013', '2012'],
            description: 'Développement, maintenance et évolution d\'un site e-commerce sous Drupal.'
        }, {
            title: 'Développeur/Animateur Web',
            company: 'Laval (Canada)',
            dates: ['2011'],
            description: 'Création de site web sous Joomla (développement, design, contenu, traduction), principalement pour des communes. Formation et création de documentation technique.'
        }
    ];

    training: {description: string, company: string, dates: string[]}[] = [
        {
            company: 'Licence Pro SIL',
            description: 'Métiers de l\'internet et des applications multimédia',
            dates: ['2013', '2012']
        }, {
            company: 'BTS IRIS',
            description: 'Informatique et réseau pour l\'industrie et les services',
            dates: ['2012', '2010']
        }
    ];

    themes: {name: string, icon?: FeatherIconNames, icons?: FeatherIconNames[], action: Function}[] = [
        {name: 'Clair', icon: 'sun', action: () => this.setTheme('light')},
        {name: 'Sombre', icon: 'moon', action: () => this.setTheme('dark')},
        {name: 'Système', icons: ['sun', 'moon'], action: () => this.setTheme(undefined)}
    ];

    theme: Theme = localStorage.getItem('theme') as Theme;

    isMd: boolean = false;

    constructor() { 
        
        this.onResize();

        this.onMedia('(prefers-color-scheme: dark)')
            .subscribe(() => setTimeout(() => (window as ThemableWindow).updateTheme(), 0));
    }

    ngAfterViewInit(): void {

        if(!matchMedia('print').matches && !matchMedia('(prefers-reduced-motion)').matches) {
            Scrollreveal().reveal('.reveal-profile .reveal', {interval: 100, distance: '80px'});
            Scrollreveal().reveal('.reveal-cards .reveal-title', {interval: 100, distance: '80px', origin: 'right'});
            Scrollreveal().reveal('.reveal-cards .reveal', {interval: 100, scale: .8, opacity: 0});
            Scrollreveal().reveal('.reveal-list .reveal-title', {interval: 100, distance: '80px', origin: 'right'});
            Scrollreveal().reveal('.reveal-list .reveal-date', {interval: 100, opacity: 0});
            Scrollreveal().reveal('.reveal-list .reveal', {interval: 100, distance: '80px', origin: 'right'});
        }
    }

    mailMe () {
        location.href = 'mailto:' + ['contact@quentindion', 'me'].join('.');
    }

    setTheme (value: Theme) {

        if(value) localStorage.setItem('theme', value);
        else localStorage.removeItem('theme');

        this.theme = value;

        (window as ThemableWindow).updateTheme();
    }

    onMedia (query: string): Observable<Boolean> {

        const mediaQuery = matchMedia(query);
        
        return fromEvent<MediaQueryList>(mediaQuery, 'change').pipe(
            startWith(mediaQuery),
            map((list: MediaQueryList) => list.matches)
        );
    }
}

<ng-template #themeMenuTemplate>
    <ul class="p-3 my-2 rounded-3xl shadow-primer-xl bg-white dark:text-gray-200 dark:bg-gray-900" @panel>
        <li *ngFor="let item of themes" (click)="item.action()"
            class="button font-normal">
            <ng-container [ngSwitch]="item.icon">
                <i *ngIf="item.icon" class="inline-block align-sub mr-2">{{item.icon}}</i>
                <span *ngIf="item.icons" class="inline-block align-text-bottom mr-2 feather-mix-to-br">
                    <i *ngFor="let icon of item.icons" class="text-gray-800 dark:text-gray-200">{{icon}}</i>
                </span>
                {{item.name}}
            </ng-container>
        </li>
    </ul>
</ng-template>

<ng-template #timelineTemplate let-items>
    <div class="w-full grid grid-cols-1-1-3 gap-6">
        <ng-container *ngFor="let item of items">
            <div>
                <h3 class="text-gray-600 dark:text-gray-400 text-right text-2xl md:text-3xl reveal-date" *ngFor="let date of item.dates">{{date}}</h3>
            </div>
            <span class="w-full h-0.5 mt-5 border-b-4 border-gray-300 dark:border-gray-700 border-dotted reveal-date"></span>
            <div>
                <h3 class="text-gray-700 dark:text-gray-300 text-3xl md:text-4xl mb-5 reveal">{{item.company}}</h3>
                <h4 class="font-medium text-gray-700 dark:text-gray-300 text-lg mb-4 reveal">{{item.title}}</h4>
                <p class="text-gray-600 dark:text-gray-400 text-sm md:text-base reveal">{{item.description}}</p>
            </div>
        </ng-container>
    </div>
</ng-template>

<section class="h-20"></section>

<section class="mx-auto sticky top-0 z-10 max-w-screen-xl container backdrop-blur-md"
    [ngStyle]="{
        'maxWidth.%': navScrollProgress.percentBetween(isMd ? 50 : 75, 100),
        'borderRadius.px': navScrollProgress.percentBetween(0, 40, true),
        'backgroundColor': 'rgb(var(--nav-background-color) / '+ navScrollProgress.percentBetween(0, 50) +'%)',
        'boxShadow': '0 '+ navScrollProgress.percentBetween(0, 8) +'px '+ navScrollProgress.percentBetween(0, 24) +'px 0 rgb(var(--shadow-primer-color) / 20%)'
    }">
    <nav class="flex items-center justify-between p-4">
        <div class="flex flex-row gap-2">
            <a class="icon button rounded-full" (click)="mailMe()" role="navigation" aria-label="Mail">
                <i>at-sign</i>
            </a>
            <a class="icon button rounded-full" href="https://www.linkedin.com/in/quentindion" role="navigation" aria-label="LinkedIn">
                <i>linkedin</i>
            </a>
            <a class="icon button rounded-full" href="https://github.com/quentindion" role="navigation" aria-label="Github">
                <i>github</i>
            </a>
            <a class="icon button rounded-full" href="https://www.youtube.com/@vs2kf" role="navigation" aria-label="Youtube">
                <i>youtube</i>
            </a>
        </div>
        <div class="flex gap-2">
            <button [dropdownTriggerFor]="themeMenuTemplate" class="icon rounded-full" aria-label="Switch dark mode">
                <span class="feather-mix-to-br">
                    <i class="text-gray-800 dark:text-gray-200">sun</i>
                    <i class="text-gray-800 dark:text-gray-200">moon</i>
                </span>
            </button>
        </div>
    </nav>
</section>

<section class="justify-center py-10 md:py-16 reveal-profile">

    <img src= "assets/profil.webp" alt="Image" class="h-[262px] w-[262px] mx-auto my-8 object-cover object-[center_60%] rounded-full reveal" loading="lazy" />
    <h1 class="flex justify-center text-gray-600 dark:text-gray-400 text-lg md:text-2xl mb-8 reveal">Quentin Dion</h1>

    <h2 class="flex justify-center md:font-light text-4xl md:text-7xl leading-none mb-8 text-transparent bg-clip-text
        bg-gradient-to-br from-lime-300 to-gray-300 to-50% dark:from-lime-300/50 dark:to-gray-700 reveal">Lead Web Developer</h2>
    <p class="flex justify-center text-gray-600 dark:text-gray-400 mb-10 md:mb-16 px-4 reveal">
        Depuis {{seniority}}ans, passionné d’informatique et des nouvelles technologies qui font le web d'aujourd'hui
    </p>
    <div class="mouse mx-auto reveal"></div>
</section>

<section class="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 reveal-cards">
    <h3 class="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl mb-5 reveal-title">Compétences</h3>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div *ngFor="let skill of skills" class="bg-gray-50 dark:bg-gray-900 px-6 py-8 rounded-xl shadow-primer-lg reveal">
            <div class="flex flex-row items-start gap-4">
                <i class="w-20 min-w-[5rem] py-6 flex justify-center bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300 rounded-xl mb-4 shadow-inner">
                    {{skill.icon}}
                </i>
                <div>
                    <h4 class="font-medium text-gray-700 dark:text-gray-300 text-lg mb-4">{{skill.category}}</h4>
                    <div class="text-gray-600 dark:text-gray-400 text-md flex flex-row flex-wrap gap-1">
                        <span *ngFor="let item of skill.items" class="bg-gray-100 dark:bg-gray-800 text-xs text-center font-medium px-2 py-1 rounded-xl">
                            {{item}}
                        </span>
                    </div>
                </div>
            </div>
            <p class="text-gray-600 dark:text-gray-400 text-md">{{skill.description}}</p>
        </div>
    </div>
</section>
    
<section class="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 reveal-list">
    <div class="flex flex-col lg:flex-row justify-between gap-6">
        <div class="mb-10 lg:mb-0">
            <h3 class="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl reveal-title">Expériences</h3>
        </div>
        <ng-container *ngTemplateOutlet="timelineTemplate; context: {$implicit: experiences}"></ng-container>
    </div>
</section>

<section class="container max-w-screen-xl mx-auto px-4 py-10 md:py-16 reveal-list">
    <div class="flex flex-col lg:flex-row justify-between gap-6">
        <div class="mb-10 lg:mb-0">
            <h3 class="font-light text-gray-700 dark:text-gray-300 text-3xl md:text-4xl reveal-title">Formations</h3>
        </div>
        <ng-container *ngTemplateOutlet="timelineTemplate; context: {$implicit: training}"></ng-container>
    </div>
</section>
